[tool.poetry]
name = "elk-apm-stack-lab"
version = "0.1.0"
description = ""
authors = ["Jairo JM Quispe <joelquispeunju@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
